spring:
  application:
    name: sip3-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://gulincastellsmatias_db_user:zzQH5UOqXMMpwpGW@sip-3.ca4ddta.mongodb.net/sip3db?appName=SIP-3}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:ZGVmYXVsdFNpcDNKd3RTZWNyZXRLZXlGb3JEZXZlbG9wbWVudA==}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    org.springframework.security: INFO